# Generated by Django 5.1 on 2024-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_event_task_has_subtasks_task_subtasks_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=28, max_length=255),
            preserve_default=False,
        ),
    ]
