# Generated by Django 5.1 on 2024-12-26 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_subtask_event_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks_description',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='members.subtask'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
