site_name: Documentação Mamutes do Cerrado

nav:
  - Landing Page: "landing.html"
  - Apresentação: index.md

  - Atas:
      - Cliente:
          - Ata 1: "atas-reuniao/cliente/ata-reuniao-1.md"
          - Ata 2: "atas-reuniao/cliente/ata-reuniao-2.md"
          - Ata 3: "atas-reuniao/cliente/ata-reuniao-3.md"
          - Ata 4: "atas-reuniao/cliente/ata-reuniao-4.md"
          - Ata 5: "atas-reuniao/cliente/ata-reuniao-5.md"
          - Ata 6: "atas-reuniao/cliente/ata-reuniao-6.md"

      - Equipe:
          - Ata 1: "atas-reuniao/equipe/ata-reuniao-1-equipe.md"
          - Ata 2: "atas-reuniao/equipe/ata-reuniao-2-equipe.md"
          - Ata 3: "atas-reuniao/equipe/ata-reuniao-3-equipe.md"
          - Ata 4: "atas-reuniao/equipe/ata-reuniao-4-equipe.md"
          - Ata 5: "atas-reuniao/equipe/ata-reuniao-5-equipe.md"
          - Ata 6: "atas-reuniao/equipe/ata-reuniao-6-equipe.md"
          - Ata 7: "atas-reuniao/equipe/ata-reuniao-7-equipe.md"

  - Documentação:
      - Visão Geral: "documento-visao/documento-visao.md"
      - Arquitetura: "documento-arquitetura/documento-arquitetura.md"

  - Links: "links/links.md"

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

  palette:
    # Paleta para modo claro
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    # Paleta para modo escuro
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

styles_css:
  - view/css/styles.css
