# Generated by Django 5.1.4 on 2025-01-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
