# Generated by Django 5.1 on 2024-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='fullname',
            field=models.CharField(default='phon', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
