# Generated by Django 5.1 on 2024-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_membroequipe_fullname_alter_membroequipe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='area',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='funcao',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
