# Generated by Django 5.1.4 on 2024-12-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_area_function_membroequipe_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
